### ISSUE TITLE
Exception while importing issues from YouTrack to Space

### ISSUE THREAD

**Issue by edwardzieminski** [JetBrains/space-issues-import#5]
Hello,

I am trying to pull my issues from YouTrack to Space, but it ends up with an exception. I bet it is because my YouTrack is attached to a custom domain. Anyways I tried to put both custom domain and standard one as an argument, but in both cases it ends up in the same way.

## My script
```bash
docker run public.registry.jetbrains.space/p/space/containers/space-issues-import:latest 
--youtrackServer https://youtrack.cofete.software/youtrack 
--spaceServer http://cofetesoft.jetbrains.space 
--spaceToken ....... 
--spaceProject key::GOFIO 
--youtrackQuery "project: Gofio" 
--youtrackToken ........ 
--updateExistingIssues 
--replaceMissingStatus 
--replaceMissingAssignee
```

## The exception
```
2021-06-25 19:11:07.792 [main] INFO  c.j.s.i.y.YoutrackIssuesLoader - issue 1 / 1
2021-06-25 19:11:07.793 [main] INFO  c.j.s.i.y.YoutrackIssuesLoader - id                GOFIO-1
2021-06-25 19:11:07.794 [main] INFO  c.j.s.i.y.YoutrackIssuesLoader - status            unknown
2021-06-25 19:11:07.794 [main] INFO  c.j.s.i.y.YoutrackIssuesLoader - assignee          Edward Zieminski
2021-06-25 19:11:07.794 [main] INFO  c.j.s.i.y.YoutrackIssuesLoader - summary           MS Excel <-> model (OpenXML based)
2021-06-25 19:11:07.797 [main] INFO  c.j.s.i.y.YoutrackIssuesLoader - description       ...
2021-06-25 19:11:07.797 [main] INFO  c.j.s.i.y.YoutrackIssuesLoader - ---
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
"; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1902)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4043)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2552)
        at space.jetbrains.api.runtime.JsonValueJvmKt.parseJson(JsonValueJvm.kt:9)
        at space.jetbrains.api.runtime.SpaceHttpClient.call(SpaceHttpClient.kt:111)
        at space.jetbrains.api.runtime.SpaceHttpClient$call$1.invokeSuspend(SpaceHttpClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.jetbrains.space.import.MainKt$main$1.invoke(main.kt:23)
        at com.jetbrains.space.import.MainKt$main$1.invoke(main.kt)
        at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
        at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
        at com.jetbrains.space.import.MainKt.main(main.kt:16)
```

**Comment by JSBmanD** [comment]
@edwardzieminski did you resolve that problem? I have json error but I think they have the same starting point.

**Comment by edwardzieminski** [comment]
@JSBmanD unfortunately I did not. Also it seems to me that this project is abandoned.

**Comment by dimart** [comment]
@edwardzieminski sorry for the late reply. If you still experience the issue, could your please run the same script using `https` in the Space server URL? Like so `--spaceServer https://cofetesoft.jetbrains.space`

If this does not help, try passing `--debug` option to the script.

**Comment by ghost** [comment]
@dimart same problem here and this did solve the problem, thanks! 😍

**Comment by dimart** [comment]
@gabriellacerda awesome! I'll close the issue then, and we will improve the error message. :)
